// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: room/v1/room.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 房间类型
type RoomType int32

const (
	RoomType_ROOM_TYPE_UNKNOWN RoomType = 0
	RoomType_ROOM_TYPE_GROUP   RoomType = 1 // 普通群聊
	RoomType_ROOM_TYPE_VOICE   RoomType = 2 // 语音房
	RoomType_ROOM_TYPE_VIDEO   RoomType = 3 // 视频房
	RoomType_ROOM_TYPE_LIVE    RoomType = 4 // 直播间
)

// Enum value maps for RoomType.
var (
	RoomType_name = map[int32]string{
		0: "ROOM_TYPE_UNKNOWN",
		1: "ROOM_TYPE_GROUP",
		2: "ROOM_TYPE_VOICE",
		3: "ROOM_TYPE_VIDEO",
		4: "ROOM_TYPE_LIVE",
	}
	RoomType_value = map[string]int32{
		"ROOM_TYPE_UNKNOWN": 0,
		"ROOM_TYPE_GROUP":   1,
		"ROOM_TYPE_VOICE":   2,
		"ROOM_TYPE_VIDEO":   3,
		"ROOM_TYPE_LIVE":    4,
	}
)

func (x RoomType) Enum() *RoomType {
	p := new(RoomType)
	*p = x
	return p
}

func (x RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[0].Descriptor()
}

func (RoomType) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[0]
}

func (x RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomType.Descriptor instead.
func (RoomType) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

// 房间状态
type RoomStatus int32

const (
	RoomStatus_ROOM_STATUS_UNKNOWN RoomStatus = 0
	RoomStatus_ROOM_STATUS_NORMAL  RoomStatus = 1 // 正常
	RoomStatus_ROOM_STATUS_MUTED   RoomStatus = 2 // 禁言
	RoomStatus_ROOM_STATUS_BANNED  RoomStatus = 3 // 封禁
)

// Enum value maps for RoomStatus.
var (
	RoomStatus_name = map[int32]string{
		0: "ROOM_STATUS_UNKNOWN",
		1: "ROOM_STATUS_NORMAL",
		2: "ROOM_STATUS_MUTED",
		3: "ROOM_STATUS_BANNED",
	}
	RoomStatus_value = map[string]int32{
		"ROOM_STATUS_UNKNOWN": 0,
		"ROOM_STATUS_NORMAL":  1,
		"ROOM_STATUS_MUTED":   2,
		"ROOM_STATUS_BANNED":  3,
	}
)

func (x RoomStatus) Enum() *RoomStatus {
	p := new(RoomStatus)
	*p = x
	return p
}

func (x RoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[1].Descriptor()
}

func (RoomStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[1]
}

func (x RoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStatus.Descriptor instead.
func (RoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

// 成员角色
type MemberRole int32

const (
	MemberRole_ROLE_UNKNOWN MemberRole = 0
	MemberRole_ROLE_MEMBER  MemberRole = 1 // 普通成员
	MemberRole_ROLE_ADMIN   MemberRole = 2 // 管理员
	MemberRole_ROLE_OWNER   MemberRole = 3 // 房主
)

// Enum value maps for MemberRole.
var (
	MemberRole_name = map[int32]string{
		0: "ROLE_UNKNOWN",
		1: "ROLE_MEMBER",
		2: "ROLE_ADMIN",
		3: "ROLE_OWNER",
	}
	MemberRole_value = map[string]int32{
		"ROLE_UNKNOWN": 0,
		"ROLE_MEMBER":  1,
		"ROLE_ADMIN":   2,
		"ROLE_OWNER":   3,
	}
)

func (x MemberRole) Enum() *MemberRole {
	p := new(MemberRole)
	*p = x
	return p
}

func (x MemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[2].Descriptor()
}

func (MemberRole) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[2]
}

func (x MemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberRole.Descriptor instead.
func (MemberRole) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

// 成员状态
type MemberStatus int32

const (
	MemberStatus_MEMBER_STATUS_UNKNOWN MemberStatus = 0
	MemberStatus_MEMBER_STATUS_NORMAL  MemberStatus = 1 // 正常
	MemberStatus_MEMBER_STATUS_MUTED   MemberStatus = 2 // 禁言中
	MemberStatus_MEMBER_STATUS_LEFT    MemberStatus = 3 // 已离开
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MEMBER_STATUS_UNKNOWN",
		1: "MEMBER_STATUS_NORMAL",
		2: "MEMBER_STATUS_MUTED",
		3: "MEMBER_STATUS_LEFT",
	}
	MemberStatus_value = map[string]int32{
		"MEMBER_STATUS_UNKNOWN": 0,
		"MEMBER_STATUS_NORMAL":  1,
		"MEMBER_STATUS_MUTED":   2,
		"MEMBER_STATUS_LEFT":    3,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[3].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[3]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

// 消息类型
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNKNOWN MessageType = 0
	MessageType_MESSAGE_TYPE_TEXT    MessageType = 1 // 文本消息
	MessageType_MESSAGE_TYPE_IMAGE   MessageType = 2 // 图片消息（预留）
	MessageType_MESSAGE_TYPE_VOICE   MessageType = 3 // 语音消息（预留）
	MessageType_MESSAGE_TYPE_VIDEO   MessageType = 4 // 视频消息（预留）
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNKNOWN",
		1: "MESSAGE_TYPE_TEXT",
		2: "MESSAGE_TYPE_IMAGE",
		3: "MESSAGE_TYPE_VOICE",
		4: "MESSAGE_TYPE_VIDEO",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN": 0,
		"MESSAGE_TYPE_TEXT":    1,
		"MESSAGE_TYPE_IMAGE":   2,
		"MESSAGE_TYPE_VOICE":   3,
		"MESSAGE_TYPE_VIDEO":   4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_room_v1_room_proto_enumTypes[4].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_room_v1_room_proto_enumTypes[4]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

// 房间信息
type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Type          RoomType               `protobuf:"varint,4,opt,name=type,proto3,enum=room.v1.RoomType" json:"type,omitempty"`
	MaxCount      int32                  `protobuf:"varint,5,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	CurrentCount  int32                  `protobuf:"varint,6,opt,name=current_count,json=currentCount,proto3" json:"current_count,omitempty"`
	Avatar        string                 `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic      bool                   `protobuf:"varint,10,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	Status        RoomStatus             `protobuf:"varint,11,opt,name=status,proto3,enum=room.v1.RoomStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_room_v1_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Room) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Room) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Room) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNKNOWN
}

func (x *Room) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *Room) GetCurrentCount() int32 {
	if x != nil {
		return x.CurrentCount
	}
	return 0
}

func (x *Room) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Room) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Room) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Room) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Room) GetStatus() RoomStatus {
	if x != nil {
		return x.Status
	}
	return RoomStatus_ROOM_STATUS_UNKNOWN
}

func (x *Room) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Room) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 房间成员信息
type RoomMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          MemberRole             `protobuf:"varint,4,opt,name=role,proto3,enum=room.v1.MemberRole" json:"role,omitempty"`
	Status        MemberStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=room.v1.MemberStatus" json:"status,omitempty"`
	MuteUntil     int64                  `protobuf:"varint,6,opt,name=mute_until,json=muteUntil,proto3" json:"mute_until,omitempty"` // Unix timestamp, 0 means not muted
	JoinedAt      int64                  `protobuf:"varint,7,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomMember) Reset() {
	*x = RoomMember{}
	mi := &file_room_v1_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomMember) ProtoMessage() {}

func (x *RoomMember) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomMember.ProtoReflect.Descriptor instead.
func (*RoomMember) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomMember) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RoomMember) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_ROLE_UNKNOWN
}

func (x *RoomMember) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNKNOWN
}

func (x *RoomMember) GetMuteUntil() int64 {
	if x != nil {
		return x.MuteUntil
	}
	return 0
}

func (x *RoomMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

func (x *RoomMember) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建房间请求
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          RoomType               `protobuf:"varint,2,opt,name=type,proto3,enum=room.v1.RoomType" json:"type,omitempty"`
	MaxCount      int32                  `protobuf:"varint,3,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoomRequest) GetType() RoomType {
	if x != nil {
		return x.Type
	}
	return RoomType_ROOM_TYPE_UNKNOWN
}

func (x *CreateRoomRequest) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

func (x *CreateRoomRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateRoomRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// 创建房间响应
type CreateRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomReply) Reset() {
	*x = CreateRoomReply{}
	mi := &file_room_v1_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomReply) ProtoMessage() {}

func (x *CreateRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomReply.ProtoReflect.Descriptor instead.
func (*CreateRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomReply) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// 获取房间请求
type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoomRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取房间响应
type GetRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomReply) Reset() {
	*x = GetRoomReply{}
	mi := &file_room_v1_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomReply) ProtoMessage() {}

func (x *GetRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomReply.ProtoReflect.Descriptor instead.
func (*GetRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoomReply) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// 更新房间请求
type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	IsPublic      bool                   `protobuf:"varint,6,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRoomRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoomRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateRoomRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoomRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateRoomRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

// 更新房间响应
type UpdateRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *Room                  `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomReply) Reset() {
	*x = UpdateRoomReply{}
	mi := &file_room_v1_room_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomReply) ProtoMessage() {}

func (x *UpdateRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomReply.ProtoReflect.Descriptor instead.
func (*UpdateRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoomReply) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// 删除房间请求
type DeleteRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomRequest) Reset() {
	*x = DeleteRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomRequest) ProtoMessage() {}

func (x *DeleteRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRoomRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除房间响应
type DeleteRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomReply) Reset() {
	*x = DeleteRoomReply{}
	mi := &file_room_v1_room_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomReply) ProtoMessage() {}

func (x *DeleteRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomReply.ProtoReflect.Descriptor instead.
func (*DeleteRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoomReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 加入房间请求
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 加入房间响应
type JoinRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *RoomMember            `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Room          *Room                  `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomReply) Reset() {
	*x = JoinRoomReply{}
	mi := &file_room_v1_room_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomReply) ProtoMessage() {}

func (x *JoinRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomReply.ProtoReflect.Descriptor instead.
func (*JoinRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{11}
}

func (x *JoinRoomReply) GetMember() *RoomMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *JoinRoomReply) GetRoom() *Room {
	if x != nil {
		return x.Room
	}
	return nil
}

// 退出房间请求
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_room_v1_room_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveRoomRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

// 退出房间响应
type LeaveRoomReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomReply) Reset() {
	*x = LeaveRoomReply{}
	mi := &file_room_v1_room_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomReply) ProtoMessage() {}

func (x *LeaveRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomReply.ProtoReflect.Descriptor instead.
func (*LeaveRoomReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{13}
}

func (x *LeaveRoomReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取成员列表请求
type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // Page number, default 1
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Page size, default 50, max 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_room_v1_room_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{14}
}

func (x *ListMembersRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *ListMembersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取成员列表响应
type ListMembersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*RoomMember          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersReply) Reset() {
	*x = ListMembersReply{}
	mi := &file_room_v1_room_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersReply) ProtoMessage() {}

func (x *ListMembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersReply.ProtoReflect.Descriptor instead.
func (*ListMembersReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{15}
}

func (x *ListMembersReply) GetMembers() []*RoomMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 踢出成员请求
type KickMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberRequest) Reset() {
	*x = KickMemberRequest{}
	mi := &file_room_v1_room_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberRequest) ProtoMessage() {}

func (x *KickMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberRequest.ProtoReflect.Descriptor instead.
func (*KickMemberRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{16}
}

func (x *KickMemberRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *KickMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 踢出成员响应
type KickMemberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickMemberReply) Reset() {
	*x = KickMemberReply{}
	mi := &file_room_v1_room_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickMemberReply) ProtoMessage() {}

func (x *KickMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickMemberReply.ProtoReflect.Descriptor instead.
func (*KickMemberReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{17}
}

func (x *KickMemberReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 更新成员角色请求
type UpdateMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          MemberRole             `protobuf:"varint,3,opt,name=role,proto3,enum=room.v1.MemberRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_room_v1_room_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateMemberRoleRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *UpdateMemberRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateMemberRoleRequest) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_ROLE_UNKNOWN
}

// 更新成员角色响应
type UpdateMemberRoleReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleReply) Reset() {
	*x = UpdateMemberRoleReply{}
	mi := &file_room_v1_room_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleReply) ProtoMessage() {}

func (x *UpdateMemberRoleReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleReply.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateMemberRoleReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 禁言/解禁成员请求
type MuteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MuteUntil     int64                  `protobuf:"varint,3,opt,name=mute_until,json=muteUntil,proto3" json:"mute_until,omitempty"` // Unix timestamp, 0 means unmute
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberRequest) Reset() {
	*x = MuteMemberRequest{}
	mi := &file_room_v1_room_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberRequest) ProtoMessage() {}

func (x *MuteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberRequest.ProtoReflect.Descriptor instead.
func (*MuteMemberRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{20}
}

func (x *MuteMemberRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *MuteMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MuteMemberRequest) GetMuteUntil() int64 {
	if x != nil {
		return x.MuteUntil
	}
	return 0
}

// 禁言/解禁成员响应
type MuteMemberReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberReply) Reset() {
	*x = MuteMemberReply{}
	mi := &file_room_v1_room_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberReply) ProtoMessage() {}

func (x *MuteMemberReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberReply.ProtoReflect.Descriptor instead.
func (*MuteMemberReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{21}
}

func (x *MuteMemberReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取用户房间列表请求
type ListUserRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoomsRequest) Reset() {
	*x = ListUserRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoomsRequest) ProtoMessage() {}

func (x *ListUserRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListUserRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{22}
}

func (x *ListUserRoomsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserRoomsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserRoomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取用户房间列表响应
type ListUserRoomsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRoomsReply) Reset() {
	*x = ListUserRoomsReply{}
	mi := &file_room_v1_room_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRoomsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRoomsReply) ProtoMessage() {}

func (x *ListUserRoomsReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRoomsReply.ProtoReflect.Descriptor instead.
func (*ListUserRoomsReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{23}
}

func (x *ListUserRoomsReply) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListUserRoomsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取所有房间列表请求
type ListAllRoomsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // Page number, default 1
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Page size, default 20, max 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllRoomsRequest) Reset() {
	*x = ListAllRoomsRequest{}
	mi := &file_room_v1_room_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllRoomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllRoomsRequest) ProtoMessage() {}

func (x *ListAllRoomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllRoomsRequest.ProtoReflect.Descriptor instead.
func (*ListAllRoomsRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{24}
}

func (x *ListAllRoomsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAllRoomsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取所有房间列表响应
type ListAllRoomsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*Room                `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllRoomsReply) Reset() {
	*x = ListAllRoomsReply{}
	mi := &file_room_v1_room_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllRoomsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllRoomsReply) ProtoMessage() {}

func (x *ListAllRoomsReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllRoomsReply.ProtoReflect.Descriptor instead.
func (*ListAllRoomsReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{25}
}

func (x *ListAllRoomsReply) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

func (x *ListAllRoomsReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 消息信息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoomId        int64                  `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=room.v1.MessageType" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_room_v1_room_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{26}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// 发送消息请求
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Type          MessageType            `protobuf:"varint,3,opt,name=type,proto3,enum=room.v1.MessageType" json:"type,omitempty"` // 默认为文本消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_room_v1_room_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{27}
}

func (x *SendMessageRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

// 发送消息响应
type SendMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_room_v1_room_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{28}
}

func (x *SendMessageReply) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// 获取消息历史请求
type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int64                  `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`                         // Page number, default 1
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // Page size, default 50, max 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_room_v1_room_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{29}
}

func (x *GetMessagesRequest) GetRoomId() int64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *GetMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessagesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取消息历史响应
type GetMessagesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesReply) Reset() {
	*x = GetMessagesReply{}
	mi := &file_room_v1_room_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesReply) ProtoMessage() {}

func (x *GetMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_room_v1_room_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesReply.ProtoReflect.Descriptor instead.
func (*GetMessagesReply) Descriptor() ([]byte, []int) {
	return file_room_v1_room_proto_rawDescGZIP(), []int{30}
}

func (x *GetMessagesReply) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesReply) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_room_v1_room_proto protoreflect.FileDescriptor

const file_room_v1_room_proto_rawDesc = "" +
	"\n" +
	"\x12room/v1/room.proto\x12\aroom.v1\x1a\x1cgoogle/api/annotations.proto\"\x84\x03\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12%\n" +
	"\x04type\x18\x04 \x01(\x0e2\x11.room.v1.RoomTypeR\x04type\x12\x1b\n" +
	"\tmax_count\x18\x05 \x01(\x05R\bmaxCount\x12#\n" +
	"\rcurrent_count\x18\x06 \x01(\x05R\fcurrentCount\x12\x16\n" +
	"\x06avatar\x18\a \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\n" +
	" \x01(\bR\bisPublic\x12+\n" +
	"\x06status\x18\v \x01(\x0e2\x13.room.v1.RoomStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\"\x81\x02\n" +
	"\n" +
	"RoomMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12'\n" +
	"\x04role\x18\x04 \x01(\x0e2\x13.room.v1.MemberRoleR\x04role\x12-\n" +
	"\x06status\x18\x05 \x01(\x0e2\x15.room.v1.MemberStatusR\x06status\x12\x1d\n" +
	"\n" +
	"mute_until\x18\x06 \x01(\x03R\tmuteUntil\x12\x1b\n" +
	"\tjoined_at\x18\a \x01(\x03R\bjoinedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xd6\x01\n" +
	"\x11CreateRoomRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.room.v1.RoomTypeR\x04type\x12\x1b\n" +
	"\tmax_count\x18\x03 \x01(\x05R\bmaxCount\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\"4\n" +
	"\x0fCreateRoomReply\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\" \n" +
	"\x0eGetRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\fGetRoomReply\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"\xa2\x01\n" +
	"\x11UpdateRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x1b\n" +
	"\tis_public\x18\x06 \x01(\bR\bisPublic\"4\n" +
	"\x0fUpdateRoomReply\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.room.v1.RoomR\x04room\"#\n" +
	"\x11DeleteRoomRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"+\n" +
	"\x0fDeleteRoomReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"_\n" +
	"\rJoinRoomReply\x12+\n" +
	"\x06member\x18\x01 \x01(\v2\x13.room.v1.RoomMemberR\x06member\x12!\n" +
	"\x04room\x18\x02 \x01(\v2\r.room.v1.RoomR\x04room\"+\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\"*\n" +
	"\x0eLeaveRoomReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\x12ListMembersRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"W\n" +
	"\x10ListMembersReply\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.room.v1.RoomMemberR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"E\n" +
	"\x11KickMemberRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"+\n" +
	"\x0fKickMemberReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x17UpdateMemberRoleRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12'\n" +
	"\x04role\x18\x03 \x01(\x0e2\x13.room.v1.MemberRoleR\x04role\"1\n" +
	"\x15UpdateMemberRoleReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"d\n" +
	"\x11MuteMemberRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"mute_until\x18\x03 \x01(\x03R\tmuteUntil\"+\n" +
	"\x0fMuteMemberReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"`\n" +
	"\x14ListUserRoomsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"O\n" +
	"\x12ListUserRoomsReply\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.room.v1.RoomR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x13ListAllRoomsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"N\n" +
	"\x11ListAllRoomsReply\x12#\n" +
	"\x05rooms\x18\x01 \x03(\v2\r.room.v1.RoomR\x05rooms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xae\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x03R\x06roomId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.room.v1.MessageTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\"q\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.room.v1.MessageTypeR\x04type\">\n" +
	"\x10SendMessageReply\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.room.v1.MessageR\amessage\"^\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x03R\x06roomId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"V\n" +
	"\x10GetMessagesReply\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.room.v1.MessageR\bmessages\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total*t\n" +
	"\bRoomType\x12\x15\n" +
	"\x11ROOM_TYPE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fROOM_TYPE_GROUP\x10\x01\x12\x13\n" +
	"\x0fROOM_TYPE_VOICE\x10\x02\x12\x13\n" +
	"\x0fROOM_TYPE_VIDEO\x10\x03\x12\x12\n" +
	"\x0eROOM_TYPE_LIVE\x10\x04*l\n" +
	"\n" +
	"RoomStatus\x12\x17\n" +
	"\x13ROOM_STATUS_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ROOM_STATUS_NORMAL\x10\x01\x12\x15\n" +
	"\x11ROOM_STATUS_MUTED\x10\x02\x12\x16\n" +
	"\x12ROOM_STATUS_BANNED\x10\x03*O\n" +
	"\n" +
	"MemberRole\x12\x10\n" +
	"\fROLE_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x03*t\n" +
	"\fMemberStatus\x12\x19\n" +
	"\x15MEMBER_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14MEMBER_STATUS_NORMAL\x10\x01\x12\x17\n" +
	"\x13MEMBER_STATUS_MUTED\x10\x02\x12\x16\n" +
	"\x12MEMBER_STATUS_LEFT\x10\x03*\x86\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n" +
	"\x12MESSAGE_TYPE_IMAGE\x10\x02\x12\x16\n" +
	"\x12MESSAGE_TYPE_VOICE\x10\x03\x12\x16\n" +
	"\x12MESSAGE_TYPE_VIDEO\x10\x042\xd1\v\n" +
	"\vRoomService\x12X\n" +
	"\n" +
	"CreateRoom\x12\x1a.room.v1.CreateRoomRequest\x1a\x18.room.v1.CreateRoomReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/rooms\x12Q\n" +
	"\aGetRoom\x12\x17.room.v1.GetRoomRequest\x1a\x15.room.v1.GetRoomReply\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/rooms/{id}\x12]\n" +
	"\n" +
	"UpdateRoom\x12\x1a.room.v1.UpdateRoomRequest\x1a\x18.room.v1.UpdateRoomReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/rooms/{id}\x12Z\n" +
	"\n" +
	"DeleteRoom\x12\x1a.room.v1.DeleteRoomRequest\x1a\x18.room.v1.DeleteRoomReply\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/rooms/{id}\x12a\n" +
	"\bJoinRoom\x12\x18.room.v1.JoinRoomRequest\x1a\x16.room.v1.JoinRoomReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/rooms/{room_id}/join\x12e\n" +
	"\tLeaveRoom\x12\x19.room.v1.LeaveRoomRequest\x1a\x17.room.v1.LeaveRoomReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/rooms/{room_id}/leave\x12j\n" +
	"\vListMembers\x12\x1b.room.v1.ListMembersRequest\x1a\x19.room.v1.ListMembersReply\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/rooms/{room_id}/members\x12q\n" +
	"\n" +
	"KickMember\x12\x1a.room.v1.KickMemberRequest\x1a\x18.room.v1.KickMemberReply\"-\x82\xd3\xe4\x93\x02'*%/v1/rooms/{room_id}/members/{user_id}\x12\x8b\x01\n" +
	"\x10UpdateMemberRole\x12 .room.v1.UpdateMemberRoleRequest\x1a\x1e.room.v1.UpdateMemberRoleReply\"5\x82\xd3\xe4\x93\x02/:\x01*\x1a*/v1/rooms/{room_id}/members/{user_id}/role\x12y\n" +
	"\n" +
	"MuteMember\x12\x1a.room.v1.MuteMemberRequest\x1a\x18.room.v1.MuteMemberReply\"5\x82\xd3\xe4\x93\x02/:\x01*\x1a*/v1/rooms/{room_id}/members/{user_id}/mute\x12n\n" +
	"\rListUserRooms\x12\x1d.room.v1.ListUserRoomsRequest\x1a\x1b.room.v1.ListUserRoomsReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/users/{user_id}/rooms\x12[\n" +
	"\fListAllRooms\x12\x1c.room.v1.ListAllRoomsRequest\x1a\x1a.room.v1.ListAllRoomsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/rooms\x12n\n" +
	"\vSendMessage\x12\x1b.room.v1.SendMessageRequest\x1a\x19.room.v1.SendMessageReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/rooms/{room_id}/messages\x12k\n" +
	"\vGetMessages\x12\x1b.room.v1.GetMessagesRequest\x1a\x19.room.v1.GetMessagesReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/rooms/{room_id}/messagesB\x15Z\x13room/api/room/v1;v1b\x06proto3"

var (
	file_room_v1_room_proto_rawDescOnce sync.Once
	file_room_v1_room_proto_rawDescData []byte
)

func file_room_v1_room_proto_rawDescGZIP() []byte {
	file_room_v1_room_proto_rawDescOnce.Do(func() {
		file_room_v1_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)))
	})
	return file_room_v1_room_proto_rawDescData
}

var file_room_v1_room_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_room_v1_room_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_room_v1_room_proto_goTypes = []any{
	(RoomType)(0),                   // 0: room.v1.RoomType
	(RoomStatus)(0),                 // 1: room.v1.RoomStatus
	(MemberRole)(0),                 // 2: room.v1.MemberRole
	(MemberStatus)(0),               // 3: room.v1.MemberStatus
	(MessageType)(0),                // 4: room.v1.MessageType
	(*Room)(nil),                    // 5: room.v1.Room
	(*RoomMember)(nil),              // 6: room.v1.RoomMember
	(*CreateRoomRequest)(nil),       // 7: room.v1.CreateRoomRequest
	(*CreateRoomReply)(nil),         // 8: room.v1.CreateRoomReply
	(*GetRoomRequest)(nil),          // 9: room.v1.GetRoomRequest
	(*GetRoomReply)(nil),            // 10: room.v1.GetRoomReply
	(*UpdateRoomRequest)(nil),       // 11: room.v1.UpdateRoomRequest
	(*UpdateRoomReply)(nil),         // 12: room.v1.UpdateRoomReply
	(*DeleteRoomRequest)(nil),       // 13: room.v1.DeleteRoomRequest
	(*DeleteRoomReply)(nil),         // 14: room.v1.DeleteRoomReply
	(*JoinRoomRequest)(nil),         // 15: room.v1.JoinRoomRequest
	(*JoinRoomReply)(nil),           // 16: room.v1.JoinRoomReply
	(*LeaveRoomRequest)(nil),        // 17: room.v1.LeaveRoomRequest
	(*LeaveRoomReply)(nil),          // 18: room.v1.LeaveRoomReply
	(*ListMembersRequest)(nil),      // 19: room.v1.ListMembersRequest
	(*ListMembersReply)(nil),        // 20: room.v1.ListMembersReply
	(*KickMemberRequest)(nil),       // 21: room.v1.KickMemberRequest
	(*KickMemberReply)(nil),         // 22: room.v1.KickMemberReply
	(*UpdateMemberRoleRequest)(nil), // 23: room.v1.UpdateMemberRoleRequest
	(*UpdateMemberRoleReply)(nil),   // 24: room.v1.UpdateMemberRoleReply
	(*MuteMemberRequest)(nil),       // 25: room.v1.MuteMemberRequest
	(*MuteMemberReply)(nil),         // 26: room.v1.MuteMemberReply
	(*ListUserRoomsRequest)(nil),    // 27: room.v1.ListUserRoomsRequest
	(*ListUserRoomsReply)(nil),      // 28: room.v1.ListUserRoomsReply
	(*ListAllRoomsRequest)(nil),     // 29: room.v1.ListAllRoomsRequest
	(*ListAllRoomsReply)(nil),       // 30: room.v1.ListAllRoomsReply
	(*Message)(nil),                 // 31: room.v1.Message
	(*SendMessageRequest)(nil),      // 32: room.v1.SendMessageRequest
	(*SendMessageReply)(nil),        // 33: room.v1.SendMessageReply
	(*GetMessagesRequest)(nil),      // 34: room.v1.GetMessagesRequest
	(*GetMessagesReply)(nil),        // 35: room.v1.GetMessagesReply
}
var file_room_v1_room_proto_depIdxs = []int32{
	0,  // 0: room.v1.Room.type:type_name -> room.v1.RoomType
	1,  // 1: room.v1.Room.status:type_name -> room.v1.RoomStatus
	2,  // 2: room.v1.RoomMember.role:type_name -> room.v1.MemberRole
	3,  // 3: room.v1.RoomMember.status:type_name -> room.v1.MemberStatus
	0,  // 4: room.v1.CreateRoomRequest.type:type_name -> room.v1.RoomType
	5,  // 5: room.v1.CreateRoomReply.room:type_name -> room.v1.Room
	5,  // 6: room.v1.GetRoomReply.room:type_name -> room.v1.Room
	5,  // 7: room.v1.UpdateRoomReply.room:type_name -> room.v1.Room
	6,  // 8: room.v1.JoinRoomReply.member:type_name -> room.v1.RoomMember
	5,  // 9: room.v1.JoinRoomReply.room:type_name -> room.v1.Room
	6,  // 10: room.v1.ListMembersReply.members:type_name -> room.v1.RoomMember
	2,  // 11: room.v1.UpdateMemberRoleRequest.role:type_name -> room.v1.MemberRole
	5,  // 12: room.v1.ListUserRoomsReply.rooms:type_name -> room.v1.Room
	5,  // 13: room.v1.ListAllRoomsReply.rooms:type_name -> room.v1.Room
	4,  // 14: room.v1.Message.type:type_name -> room.v1.MessageType
	4,  // 15: room.v1.SendMessageRequest.type:type_name -> room.v1.MessageType
	31, // 16: room.v1.SendMessageReply.message:type_name -> room.v1.Message
	31, // 17: room.v1.GetMessagesReply.messages:type_name -> room.v1.Message
	7,  // 18: room.v1.RoomService.CreateRoom:input_type -> room.v1.CreateRoomRequest
	9,  // 19: room.v1.RoomService.GetRoom:input_type -> room.v1.GetRoomRequest
	11, // 20: room.v1.RoomService.UpdateRoom:input_type -> room.v1.UpdateRoomRequest
	13, // 21: room.v1.RoomService.DeleteRoom:input_type -> room.v1.DeleteRoomRequest
	15, // 22: room.v1.RoomService.JoinRoom:input_type -> room.v1.JoinRoomRequest
	17, // 23: room.v1.RoomService.LeaveRoom:input_type -> room.v1.LeaveRoomRequest
	19, // 24: room.v1.RoomService.ListMembers:input_type -> room.v1.ListMembersRequest
	21, // 25: room.v1.RoomService.KickMember:input_type -> room.v1.KickMemberRequest
	23, // 26: room.v1.RoomService.UpdateMemberRole:input_type -> room.v1.UpdateMemberRoleRequest
	25, // 27: room.v1.RoomService.MuteMember:input_type -> room.v1.MuteMemberRequest
	27, // 28: room.v1.RoomService.ListUserRooms:input_type -> room.v1.ListUserRoomsRequest
	29, // 29: room.v1.RoomService.ListAllRooms:input_type -> room.v1.ListAllRoomsRequest
	32, // 30: room.v1.RoomService.SendMessage:input_type -> room.v1.SendMessageRequest
	34, // 31: room.v1.RoomService.GetMessages:input_type -> room.v1.GetMessagesRequest
	8,  // 32: room.v1.RoomService.CreateRoom:output_type -> room.v1.CreateRoomReply
	10, // 33: room.v1.RoomService.GetRoom:output_type -> room.v1.GetRoomReply
	12, // 34: room.v1.RoomService.UpdateRoom:output_type -> room.v1.UpdateRoomReply
	14, // 35: room.v1.RoomService.DeleteRoom:output_type -> room.v1.DeleteRoomReply
	16, // 36: room.v1.RoomService.JoinRoom:output_type -> room.v1.JoinRoomReply
	18, // 37: room.v1.RoomService.LeaveRoom:output_type -> room.v1.LeaveRoomReply
	20, // 38: room.v1.RoomService.ListMembers:output_type -> room.v1.ListMembersReply
	22, // 39: room.v1.RoomService.KickMember:output_type -> room.v1.KickMemberReply
	24, // 40: room.v1.RoomService.UpdateMemberRole:output_type -> room.v1.UpdateMemberRoleReply
	26, // 41: room.v1.RoomService.MuteMember:output_type -> room.v1.MuteMemberReply
	28, // 42: room.v1.RoomService.ListUserRooms:output_type -> room.v1.ListUserRoomsReply
	30, // 43: room.v1.RoomService.ListAllRooms:output_type -> room.v1.ListAllRoomsReply
	33, // 44: room.v1.RoomService.SendMessage:output_type -> room.v1.SendMessageReply
	35, // 45: room.v1.RoomService.GetMessages:output_type -> room.v1.GetMessagesReply
	32, // [32:46] is the sub-list for method output_type
	18, // [18:32] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_room_v1_room_proto_init() }
func file_room_v1_room_proto_init() {
	if File_room_v1_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_v1_room_proto_rawDesc), len(file_room_v1_room_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_v1_room_proto_goTypes,
		DependencyIndexes: file_room_v1_room_proto_depIdxs,
		EnumInfos:         file_room_v1_room_proto_enumTypes,
		MessageInfos:      file_room_v1_room_proto_msgTypes,
	}.Build()
	File_room_v1_room_proto = out.File
	file_room_v1_room_proto_goTypes = nil
	file_room_v1_room_proto_depIdxs = nil
}
