version: '3.8'

services:
  # --- Go 服务 ---
  user-service:
    build: .
    container_name: user_dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    command: kratos run

  # --- 数据库服务 ---
  db:
    # If you are out of China, turn to use first image source
    # 切换为了使用国内镜像源，为了下载 PostgreSQL 
    #image: postgres:16-alpine
    image: docker.m.daocloud.io/library/postgres:16-alpine
    container_name: user_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=07210721
      - POSTGRES_DB=benutzer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
