version: '3.8'

services:
  # --- Container for the micro-service---
  user-service:
    build: .                 # built with Dockerfile on current dir
    container_name: user_dev # name the container 
    volumes:
      - .:/app               # [core] mount the current dir as volume upon  /app
                             
    ports:
      - "8000:8000"          # port for HTTP
      - "9000:9000"          # port for gRPC
    environment:
      # tell to the codes：adrress of database is "db" instead of "localhost"
      # Attention：you need open data.go to change the codes so it can read this env path var, or follow special notes below.    
    DB_HOST: db
    depends_on:
      - db                   # start me after the database starts
    command: kratos run      # command to start 

  # --- Container for the Database ---
  db:
    image: postgres:16-alpine
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 07210721 # this is my default password, dont chage it ! Hurray Nene Ayane !
      POSTGRES_DB: benutzer_db    # benutzer is a word in German, it means 'user '
    ports:
      - "5432:5432"               # port out, you can view it on pgAdmin4 
    volumes:
      - postgres_data:/var/lib/postgresql/data # persisting data to prevent loss after restarting

volumes:
  postgres_data:
