server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s
data:
  database:
    driver: postgres
    source: postgres://postgres:07210721@user-db:5432/benutzer_db?sslmode=disable
    max_open_conns: 100
    max_idle_conns: 10
    conn_max_lifetime: 300s
    enable_auto_migrate: true
