// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"room/internal/biz"
	"room/internal/conf"
	"room/internal/data"
	"room/internal/server"
	"room/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	confServer := wireServerProvider(bootstrap)
	confData := wireDataProvider(bootstrap)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	roomRepository := data.NewRoomRepo(dataData)
	roomUsecase := biz.NewRoomUsecase(roomRepository, logger)
	roomMemberRepository := data.NewRoomMemberRepo(dataData)
	roomMemberUsecase := biz.NewRoomMemberUsecase(roomMemberRepository, roomRepository, logger)
	messageRepository := data.NewMessageRepo(dataData)
	messageUsecase := biz.NewMessageUsecase(messageRepository, roomMemberRepository, logger)
	roomService := service.NewRoomService(roomUsecase, roomMemberUsecase, messageUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, roomService, logger)
	webSocketHub := service.NewWebSocketHub(logger)
	webSocketService := service.NewWebSocketService(webSocketHub, messageUsecase, roomMemberUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, roomService, webSocketService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

// wireServerProvider 从 Bootstrap 中提取 Server 配置
func wireServerProvider(bc *conf.Bootstrap) *conf.Server {
	return bc.Server
}

// wireDataProvider 从 Bootstrap 中提取 Data 配置
func wireDataProvider(bc *conf.Bootstrap) *conf.Data {
	return bc.Data
}
